export const products = [
    { id: 1, name: 'عكس فلات 3/4', image: 'https://via.placeholder.com/100' },
    { id: 2, name: 'صمونة فلات 3/4', image: 'https://via.placeholder.com/100' },
    { id: 3, name: 'تقسيم فلات 3/4', image: 'https://via.placeholder.com/100' },
    { id: 4, name: 'مصغر فلات 1* 3/4', image: 'https://via.placeholder.com/100' },
    { id: 5, name: 'عبارة فلات 3/4', image: 'https://via.placeholder.com/100' },
    { id: 6, name: 'بوري 3/4', image: 'https://via.placeholder.com/100' },
    { id: 7, name: 'قفل لحام 3/4', image: 'https://via.placeholder.com/100' },    
    { id: 8, name: 'قفل لحام 3/4 دبل يونين', image: 'https://via.placeholder.com/100' },    
    { id: 29, name: 'قفل سن 3/4', image: 'https://via.placeholder.com/100' },    
    { id: 21, name: 'ادبتر 3/4*1/2 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 22, name: 'ادبتر 3/4*1/2 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 23, name: 'ادبتر 3/4*3/4 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 24, name: 'ادبتر 3/4*3/4 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 25, name: 'قطع وصل 3/4*3/4 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 26, name: 'قطع وصل 3/4*3/4 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 27, name: 'تقسيم 3/4*1/2 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 29, name: 'تقسيم 3/4*1/2 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 323, name: 'تقسيم 3/4*3/4 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 32, name: 'تقسيم 3/4*3/4 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 31, name: 'عكس فلات 1', image: 'https://via.placeholder.com/100' },
    { id: 42, name: 'صمونة فلات 1', image: 'https://via.placeholder.com/100' },
    { id: 52, name: 'تقسيم فلات 1', image: 'https://via.placeholder.com/100' },
    { id: 62, name: 'مصغر فلات 1* 1', image: 'https://via.placeholder.com/100' },
    { id: 72, name: 'عبارة فلات 1', image: 'https://via.placeholder.com/100' },
    { id: 82, name: 'بوري 1', image: 'https://via.placeholder.com/100' },
    { id: 92, name: 'ادبتر 3/4*1 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 102, name: 'ادبتر 3/4*1 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 112, name: 'ادبتر 1*1 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 223, name: 'ادبتر 1*1 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 2856, name: 'قطع وصل 1*1 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 216, name: 'قطع وصل 1*1 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 256, name: 'تقسيم 3/4*1 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 216, name: 'تقسيم 3/4*1 خارجي', image: 'https://via.placeholder.com/100' },
    { id: 2, name: 'تقسيم 1*1 داخلي', image: 'https://via.placeholder.com/100' },
    { id: 2156, name: 'تقسيم 1*1 خارجي', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'قفل لحام 1', image: 'https://via.placeholder.com/100' },    
    { id: 216, name: 'قفل لحام 1 دبل يونين', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'كلي 4 انج', image: 'https://via.placeholder.com/100' },    
    { id: 215, name: 'عكس 4 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'تقسيم 4 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2156, name: 'صمونة 4 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'جطل 4 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'مصغر 4 *2.5 ', image: 'https://via.placeholder.com/100' },    
    { id: 261, name: 'مصغر 4 *1.5 ', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'مجمع كلي 4 *2.5 ', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'مجمع كلي 8 *4 ', image: 'https://via.placeholder.com/100' },
    { id: 2, name: 'كلي 2.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'عكس 2.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'تقسيم 2.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'صمونة 2.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'جطل 2.5 انج', image: 'https://via.placeholder.com/100' },
    { id: 2, name: 'كلي 1.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'عكس 1.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'تقسيم 1.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'صمونة 1.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'جطل 1.5 انج', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'كب 4', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'كب 2.5', image: 'https://via.placeholder.com/100' },    
    { id: 2, name: 'تطوالة 10 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 15 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 20 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 25 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 30 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 40 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة 50 ملم', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'تطوالة حديد 1/2', image: 'https://via.placeholder.com/100' }, 
    { id: 2, name: 'نبل  1', image: 'https://via.placeholder.com/100' }, 
       
];
